apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate-admin
  labels:
    app: pingfederate
    tier: admin
spec:
  replicas: 1
  selector:
      matchLabels:
        app: pingfederate
        tier: admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pingfederate
        tier: admin
    spec:
      containers:
      - name: console-node
        image: pingidentity/pingfederate:10.0.0-alpine-edge
        ports:
        - containerPort: 9999
        - containerPort: 7600
        resources:
          requests:
            memory: "2.5Gi"
            cpu: "2"
          limits:
            memory: "2.5Gi"
            cpu: "2"
        envFrom:
          - configMapRef:
              name: pingfederate-variables
          - secretRef:
              name: devops-secret
              optional: true
        #only used for testing pulling configs, admin will be on master/edge only
        env:
          #this is what we will update with flux. new versions will be tags!
          - name: SERVER_PROFILE_ANYDEVOPS_BRANCH
            value: v1
          - name: OPERATIONAL_MODE
            value: CLUSTERED_CONSOLE
          - name: PF_ENGINE_PUBLIC_HOSTNAME
            value: ${K8S_ENVIRONMENT}pingfederate.anydevops.com
          - name: PF_ADMIN_PUBLIC_HOSTNAME
            value: ${K8S_ENVIRONMENT}pingfederate-admin.anydevops.com
          - name: PF_ENGINE_PUBLIC_PORT
            value: "443"