apiVersion: v1
data:
  CLUSTER_BIND_ADDRESS: NON_LOOPBACK
  CLUSTER_NAME: anydevops
  DNS_QUERY_LOCATION: _bind-port._tcp.pf-cluster.sg-dev.svc.cluster.local
  DNS_RECORD_TYPE: SRV
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_BASELINE_PARENT: THIS_REPO
  SERVER_PROFILE_BASELINE_PATH: baseline/pingfederate
  SERVER_PROFILE_BASELINE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
  SERVER_PROFILE_PARENT: BASELINE
  SERVER_PROFILE_PATH: pf-dns-ping-clustering/pingfederate
  SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
kind: ConfigMap
metadata:
  name: pingfederate-variables
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxekNDQWIrZ0F3SUJBZ0lKQUlRdC9vZmcvSmZhTUEwR0NTcUdTSWIzRFFFQkN3VUFNQm94R0RBV0JnTlYKQkFNTUQzQnBibWN0WkdWMmIzQnpMbU52YlRBZUZ3MHhPVEV4TWpFeE16TTBORE5hRncweU9URXhNVGd4TXpNMApORE5hTUJveEdEQVdCZ05WQkFNTUQzQnBibWN0WkdWMmIzQnpMbU52YlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5ZUDJlVUk4UDcwUXZJY0Q3ams4WmI5OVNFSzl0VmdCaDlIMU43SWpmUmgKazVQT3dYanRhUURseGpNS0JaTGNDUjNJVDJQQXlRcStDOWFkSWtKK1RXUzB1YVJqeUJkTDFKMHdieXhvR08wYQowRWlSaWU2dSt0NFJQb1pPZExoVWMrM1N0RENhbmpxd01zS25GbTk2ZUlhRHYzeUNJaDVtZjQrc3RvSDJBc0x2CmlSSWNCVE9pazRGTFA3WGh2MTQ4bGVQS1JNOTRmekxyRDRvbFh3cGszZ1NjOFVnNHd6ZGtwbjhER2JlVUgxM08KN20vNkV3bnppYllCTFhxeVZJSWpjQkU0L0JSVmtQTTRRYmtlWkdXUDEyUDUrUkt1SGtoK2RPUXdhWndIMG1VUwo2bFA3ZXVaaDRrOUphNzdDb0wzWm01OG5FVDNKWWVBazA1UDg0V1pqaEFrQ0F3RUFBYU1nTUI0d0hBWURWUjBSCkJCVXdFNElSS2k1d2FXNW5MV1JsZG05d2N5NWpiMjB3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUJHVkFVMGYKeWMzM0xLaE5PbnE4Y1p6WGRFNksrc2R2TSt3RUtCYmluWVFjeFB5dEx6eXV4UVJUR1I3OTVOOFczRVNlaVdzeQpZa0ZWeGVXaTk5dCtiQy9zR1VkRmEwTmdVSGtSV2U0Q1VweW51Tk94RnVBSkNIaWRFNVFLOXFmcFMrbUlhWG5zCnBTbEpOSFA1Wk9rajB3SmI4MUJWUVkxV0lvQWRJbW5aT3YxaUoyM2NyUDhWMXQrbURNQ3hiekZmQkhNcU9GekwKcmIyMkxac05MeURWbWFOb1ZXQ1FycXpNSDN5aTdEdEVJSEhkbzZyN2tPZXBnakZFbC9xVlpTQm16bHRoUWk4bgpqSlEwZ0ZWNDRsNzcvdTdiMisrZzBuRVJuTS8rWWgyYXBZMXo1aEQreWFqUWhiQlg4Z0hBZ09lZ0xQcjNISzlsClJLSWg5UTlvWXdoeFBWUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRFdEOW5sQ1BEKzlFTHkKSEErNDVQR1cvZlVoQ3ZiVllBWWZSOVRleUkzMFlaT1R6c0Y0N1drQTVjWXpDZ1dTM0FrZHlFOWp3TWtLdmd2VwpuU0pDZmsxa3RMbWtZOGdYUzlTZE1HOHNhQmp0R3RCSWtZbnVydnJlRVQ2R1RuUzRWSFB0MHJRd21wNDZzRExDCnB4WnZlbmlHZzc5OGdpSWVabitQckxhQjlnTEM3NGtTSEFVem9wT0JTeisxNGI5ZVBKWGp5a1RQZUg4eTZ3K0sKSlY4S1pONEVuUEZJT01NM1pLWi9BeG0zbEI5ZHp1NXYraE1KODRtMkFTMTZzbFNDSTNBUk9Qd1VWWkR6T0VHNQpIbVJsajlkaitma1NyaDVJZm5Ua01HbWNCOUpsRXVwVCszcm1ZZUpQU1d1K3dxQzkyWnVmSnhFOXlXSGdKTk9UCi9PRm1ZNFFKQWdNQkFBRUNnZ0VCQUpJaUdCcG5WRDU0K2dyV1pWVlAxaTNDQ1VvWmRoQ01rU0ZocEV6Q2xVWTAKSnM5TTRuOXZjN09OS1JWR3ppOUh6MkZwa2VrRGZ6dTZLZExGU3RJaDd5dkV4TWNZNTB3Z0ZIR0sweHA1cGlxWApsNEV5K2ZyYnNaOVFIbU1KeEZ6aUtwSTh1WTVFdjZoSkNSNGhld3QzakRnb1VOenE2ZWZmQ1U1SUZmLzZ0ai9rCmp3c3ZkM2EwbzBoZnoyRmNKL3Z0YkhqUWVmZFRhMUNyVlVJQ0dqU3hmYmtZa01aeFk4M1hQWTJnQ25UOCtMQ2UKVkp6SVZmczFYTXY1TmNuR0x1WjYyVTFtRjVhZ2VPcTMrUllMUmwzZGVCUllyM01vNGxDK1E1V0l5YlY1MDhGVwpkellwN0xxSjBhRHErVDFGVDUrZXArRGVFRW55QVR4R2F5WWYrTUR3RHhFQ2dZRUE2dCtvcm5XWk9qVGZrRWRoCldLeDlYeHk4T2tURWYxaTFaS1g5d1BZZEFYMzdiWDNlcjd2eXBUYjNWd0lzVHJLWHgxTmJ3eUNTdm40VmJoZVQKOGFuTEJpOUFPWGx0UXk2YnhzRE5aei9tcVUrVlczV1l5V0w0U0NuUXF0WDJjZTZ1WS80MWJXQ0VwUE9hVXVycQpNRWh1ZVl0Y3N1NVRLSVlhVVp2UHlmNDYyVE1DZ1lFQTZWRDM3NEdGUmwxUktPUDI0akpHMkVMVG5aalhBSzBECmsva09FdEJaK1lobkw1MWpTWHFhbklZKzcrM1R4R29zaHByUStFeTgzeFBRdXR4NFR2T3AwNlZTa1BVVnd2VkoKMjBVeHhINUlpVjVpaUxmS25nOCt5U3JSMG9OT2pJRGMwZUpTTTMyNWR4REV6aDdQc09mR21IcUYwQlhvcFJKUQpDMHNJOVVESmhkTUNnWUJVaEgwdm9qT3NSV0I1aTZZVkFhVHZ0K2huMDEwZU1pNjc5QnRXOTNsQ2t6SUptWFNyCnFpZExtbmJ3d1dCdVJVZm11ekZYQ3Y2ak83MjhheEdhc2EzVUlPYXNoK3h3YzNJczJDNVJ6Q1hWb1VTdXI2ZDIKT0gzOWdjYUw0d2lXd1B2U0VhVHFJZ1E1VTB1aU1OUnE0WFdYbVRXWFVibHM2S3pKMXhhenFoOUZEd0tCZ0FMRgo5cHgvTXFGYWZKdDYwalZ3R1kxNmhkOXFzS3VPWXV1QVcxMTM0b25ueUNvMXViZG00SzJabnVmbE1NNDE0TitjCnVYMHFGRmltZUtXdjl6SWhEVlM1czFpTHdUMTNBdkM3U3RNbUdTQ2c0WlQwY2xFY3AwZG0zZVdkci9KVm1jcFkKNFZkQldGSUUvZ0hoTmVESmNIL2hmUE96UHZldlZ3bzdVeGp2TXpZSEFvR0JBTHUvdE9lZ3NGY085ZFFvdmFuTQpwVm5nUExvaUF1TUwrUDh4NEFEcXFLWGx3M0F6a0hzWTF2ODlqVnZtczNaMVNhL2NBTHBUcDhxZ2UybDZVc3lVCk9hZ1FNcG5KL3ZKTWwrN3ppNWo2SWo0SnVzcGVHcm1vN0Fxck1TZStIcXpUc0Vwb1h6SHNGUVVOa0FiVVAweTAKaGwzV2R0d0tuZXllaGF4ckR0MTNNamdLCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  labels:
    domain: anydevops.com
  name: anydevops-tls-secret
type: kubernetes.io/tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pingfederate
    tier: engine
  name: pingfederate
  namespace: anydevops
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9031
  selector:
    app: pingfederate
    tier: engine
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: pingfederate
  name: pf-cluster
spec:
  clusterIP: None
  ports:
  - name: bind-port
    port: 7600
    protocol: TCP
    targetPort: 7600
  publishNotReadyAddresses: true
  selector:
    app: pingfederate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pingfederate
    tier: admin
  name: pingfederate-admin
spec:
  ports:
  - port: 9999
    protocol: TCP
  selector:
    app: pingfederate
    tier: admin
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pingfederate
    tier: engine
  name: pingfederate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingfederate
      tier: engine
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pingfederate
        tier: engine
        version: "0.1"
    spec:
      containers:
      - env:
        - name: SERVER_PROFILE_ANYDEVOPS_BRANCH
          value: v1
        - name: OPERATIONAL_MODE
          value: CLUSTERED_CONSOLE
        - name: PF_ENGINE_PUBLIC_HOSTNAME
          value: sg-dev.pingfederate.anydevops.com
        - name: PF_ADMIN_PUBLIC_HOSTNAME
          value: sg-dev.pingfederate-admin.anydevops.com
        - name: PF_ENGINE_PUBLIC_PORT
          value: "443"
        envFrom:
        - configMapRef:
            name: pingfederate
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingfederate:10.0.0
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 20
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /pf/heartbeat.ping
            port: 9031
            scheme: HTTPS
          initialDelaySeconds: 150
          periodSeconds: 1
        name: pingfederate
        ports:
        - containerPort: 9031
          name: runtime
        readinessProbe:
          httpGet:
            path: /pf/heartbeat.ping
            port: 9031
            scheme: HTTPS
          periodSeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 2.5Gi
          requests:
            cpu: "2"
            memory: 2.5Gi
      initContainers:
      - command:
        - sh
        - -c
        - until curl --connect-timeout 1 --silent -k https://pingfederate-admin:9999/pingfederate/app
          ; do echo waiting for admin ; sleep 2 ; done
        image: curlimages/curl:latest
        name: init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pingfederate
    tier: admin
  name: pingfederate-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingfederate
      tier: admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pingfederate
        tier: admin
    spec:
      containers:
      - env:
        - name: SERVER_PROFILE_ANYDEVOPS_BRANCH
          value: v1
        - name: OPERATIONAL_MODE
          value: CLUSTERED_CONSOLE
        - name: PF_ENGINE_PUBLIC_HOSTNAME
          value: sg-dev.pingfederate.anydevops.com
        - name: PF_ADMIN_PUBLIC_HOSTNAME
          value: sg-dev.pingfederate-admin.anydevops.com
        - name: PF_ENGINE_PUBLIC_PORT
          value: "443"
        envFrom:
        - configMapRef:
            name: pingfederate-variables
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingfederate:10.0.0-alpine-edge
        name: console-node
        ports:
        - containerPort: 9999
        - containerPort: 7600
        resources:
          limits:
            cpu: "2"
            memory: 2.5Gi
          requests:
            cpu: "2"
            memory: 2.5Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  labels:
    app: pingfederate
    tier: engine
  name: pingfederate
  namespace: anydevops
spec:
  rules:
  - host: sg-dev.pingfederate.anydevops.com
    http:
      paths:
      - backend:
          serviceName: pingfederate
          servicePort: 443
        path: /
  tls:
  - hosts:
    - sg-dev.pingfederate.anydevops.com
    secretName: anydevops-tls-secret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  labels:
    app: pingfederate
    tier: admin
  name: pingfederate-admin
spec:
  rules:
  - host: sg-dev.pingfederate-admin.anydevops.com
    http:
      paths:
      - backend:
          serviceName: pingfederate-admin
          servicePort: 9999
        path: /pingfederate
      - backend:
          serviceName: pingfederate-admin
          servicePort: 9999
        path: /pf-admin-api
  tls:
  - hosts:
    - sg-dev.pingfederate-admin.anydevops.com
    secretName: anydevops-tls-secret
