kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# requirements beyond 01-standalone for replication: 
#   1. additional environment variables must be passed - via replacing the configmap
#   2. number of replicas is increased - via patch
# 
#   additionally, we create a storage class and mount volumes to prepare for disasters. 

resources:
- pingdirectory.yaml
# - storage.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  envs:
    - env_vars.pingdirectory