############################################################
# Ping Identity DevOps values.yaml
############################################################
# The yaml is seperated into 2 major sections:
#  - global - Represents the base set of values that will
#             be used for each product, if that product
#             doesn't override the global values.
#
#  - image  - For every image/product, the values will
#             be merged with the global settings, and
#             take precedence.
############################################################

############################################################
# Global values
############################################################
global:
  addReleaseNameToResource: prepend
  ingress:
    enabled: true
    addReleaseNameToHost: prepend
    defaultDomain: ping-devops.com
    defaultTlsSecret:
    annotations:
      # nginx example
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx-public"
  image:
    repository: pingidentity
    name:
    tag: 2011
    pullPolicy: IfNotPresent
  license:
    secret:
      devOps: devops-secret
# REMOVE ALL THIS ONCE VARIABLES ARE DEFINED BY DEVOPS TEAM
  envs:
    PING_IDENTITY_ACCEPT_EULA: "YES"
    # PA_ADMIN_PRIVATE_PORT_ACME: "8080"
    # PA_ADMIN_PRIVATE_PORT_HTTPS: "9000"
    # PA_ADMIN_PUBLIC_PORT_HTTPS: "443"
    # PA_ENGINE_PUBLIC_PORT_HTTPS: "443"
    # PA_ENGINE_PRIVATE_HOSTNAME: ${RELEASE}-pingaccess
    # PA_ENGINE_PUBLIC_HOSTNAME: ${RELEASE}-pingaccess-admin.ping-devops.com
    # PD_DELEGATOR_HTTPS_PRIVATE_PORT: "6443"
    PD_DELEGATOR_HTTPS_PUBLIC_PORT: "443"
    # PD_DELEGATOR_PRIVATE_HOSTNAME: ${RELEASE}-pingdelegator
    # PD_DELEGATOR_PUBLIC_HOSTNAME: ${RELEASE}-pingdelegator.ping-devops.com
    # PD_ENGINE_PRIVATE_PORT_HTTPS: "443"
    # PD_ENGINE_PUBLIC_PORT_HTTPS: "443"
    # PD_ENGINE_PRIVATE_PORT_LDAP: "389"
    # PD_ENGINE_PRIVATE_PORT_LDAPS: "636"
    # PD_ENGINE_PRIVATE_HOSTNAME: ${RELEASE}-pingdirectory
    # PD_ENGINE_PUBLIC_HOSTNAME: ${RELEASE}-pingdirectory.ping-devops.com
    # PDG_ENGINE_PRIVATE_PORT_HTTPS: "443"
    # PDG_ENGINE_PUBLIC_PORT_HTTPS: "443"
    # PDG_ENGINE_PRIVATE_HOSTNAME: ${RELEASE}-pingdatagovernance
    # PDG_ENGINE_PUBLIC_HOSTNAME: ${RELEASE}-pingdatagovernance.ping-devops.com
    # PDS_ENGINE_PRIVATE_PORT_HTTPS: "443"
    # PDS_ENGINE_PRIVATE_HOSTNAME: ${RELEASE}-pingdatasync
    # PF_ADMIN_PRIVATE_PORT_HTTPS: "9999"
    # PF_ADMIN_PUBLIC_PORT_HTTPS: "443"
    # PF_ADMIN_PRIVATE_HOSTNAME: ${RELEASE}-pingfederate-admin
    # PF_ADMIN_PUBLIC_HOSTNAME: ${RELEASE}-pingfederate-admin.ping-devops.com
    # PF_ENGINE_PRIVATE_PORT_HTTPS: "9031"
    # PF_ENGINE_PUBLIC_PORT_HTTPS: "443"
    # PF_ENGINE_PRIVATE_HOSTNAME: ${RELEASE}-pingfederate-engine
    # PF_ENGINE_PUBLIC_HOSTNAME: ${RELEASE}-pingfederate-engine.ping-devops.com
#############################################################
# pingfederate-admin values
#############################################################
pingfederate-admin:
  enabled: true
  container:
    waitFor:
      pingdirectory:
        service: ldaps
  image:
    repository: pingidentity
    name: pingfederate
    tag: 10.1.3-edge
    pullPolicy: Always
  envs:
    SERVER_PROFILE_BASE_PATH: profiles/pingfederate
    SERVER_PROFILE_BASE_URL: https://github.com/pingdevopsprogram/reference-cicd
    SERVER_PROFILE_PARENT: BASE
    SERVER_PROFILE_PATH: profiles/pingfederate_admin
    SERVER_PROFILE_URL: https://github.com/pingdevopsprogram/reference-cicd
    # data.json.subst specific vars. 
    PA_ENGINE_PRIVATE_PORT_HTTPS: "3000"
    PD_DELEGATOR_HTTPS_PUBLIC_PORT: "443"
    # will change per branch
    PF_OIDC_CLIENT_ID: "c475b46d-d48f-4de1-9846-53ca0072f82a"
    PF_OIDC_CLIENT_SECRET: "D~UMY~2h7A0hxE.UuRBdGHf4BPi61javHXWLdA.Uko.hF8pKXj1cbrN_oQjnRBhg"
    # will change per account
    PF_OIDC_CLIENT_AUTHN_METHOD: client_secret_basic
    PF_OIDC_AUTHORIZATION_ENDPOINT: "https://auth.pingone.com/975eb21b-c72c-40a0-82ce-1a7fe44a5d6e/as/authorize"
    PF_OIDC_TOKEN_ENDPOINT: "https://auth.pingone.com/975eb21b-c72c-40a0-82ce-1a7fe44a5d6e/as/token"
    PF_OIDC_USER_INFO_ENDPOINT: "https://auth.pingone.com/975eb21b-c72c-40a0-82ce-1a7fe44a5d6e/as/userinfo"
    PF_OIDC_END_SESSION_ENDPOINT: "https://auth.pingone.com/975eb21b-c72c-40a0-82ce-1a7fe44a5d6e/as/signoff"
    PF_OIDC_ISSUER: https://auth.pingone.com/975eb21b-c72c-40a0-82ce-1a7fe44a5d6e/as
    # PF_OIDC_ACR_VALUES:
    PF_OIDC_SCOPES: openid email profile
    PF_OIDC_USERNAME_ATTRIBUTE_NAME: name
    PF_OIDC_ROLE_ATTRIBUTE_NAME: pf-admin-roles
    PF_OIDC_ROLE_ADMIN: fullAdmin
    PF_OIDC_ROLE_CRYPTOMANAGER: fullAdmin
    PF_OIDC_ROLE_USERADMIN: fullAdmin
    PF_OIDC_ROLE_EXPRESSIONADMIN: fullAdmin
    PF_OIDC_ROLE_AUDITOR: fullAdmin
#############################################################
# pingfederate-engine values
#############################################################
pingfederate-engine:
  enabled: true
  image:
    repository: pingidentity
    name: pingfederate
    tag: 10.1.3-edge
    pullPolicy: Always
  envs:
    SERVER_PROFILE_PATH: profiles/pingfederate
    SERVER_PROFILE_URL: https://github.com/pingdevopsprogram/reference-cicd
    PF_LOG_LEVEL: DEBUG
    # will change per branch
    PF_OIDC_CLIENT_ID: "c475b46d-d48f-4de1-9846-53ca0072f82a"
    PF_OIDC_CLIENT_SECRET: "D~UMY~2h7A0hxE.UuRBdGHf4BPi61javHXWLdA.Uko.hF8pKXj1cbrN_oQjnRBhg"
    # will change per account
    PF_OIDC_CLIENT_AUTHN_METHOD: client_secret_basic
    PF_OIDC_AUTHORIZATION_ENDPOINT: "https://auth.pingone.com/975eb21b-c72c-40a0-82ce-1a7fe44a5d6e/as/authorize"
    PF_OIDC_TOKEN_ENDPOINT: "https://auth.pingone.com/975eb21b-c72c-40a0-82ce-1a7fe44a5d6e/as/token"
    PF_OIDC_USER_INFO_ENDPOINT: "https://auth.pingone.com/975eb21b-c72c-40a0-82ce-1a7fe44a5d6e/as/userinfo"
    PF_OIDC_END_SESSION_ENDPOINT: "https://auth.pingone.com/975eb21b-c72c-40a0-82ce-1a7fe44a5d6e/as/signoff"
    PF_OIDC_ISSUER: https://auth.pingone.com/975eb21b-c72c-40a0-82ce-1a7fe44a5d6e/as
    # PF_OIDC_ACR_VALUES:
    PF_OIDC_SCOPES: openid email profile
    PF_OIDC_USERNAME_ATTRIBUTE_NAME: name
    PF_OIDC_ROLE_ATTRIBUTE_NAME: pf-admin-roles
    PF_OIDC_ROLE_ADMIN: fullAdmin
    PF_OIDC_ROLE_CRYPTOMANAGER: fullAdmin
    PF_OIDC_ROLE_USERADMIN: fullAdmin
    PF_OIDC_ROLE_EXPRESSIONADMIN: fullAdmin
    PF_OIDC_ROLE_AUDITOR: fullAdmin
  clustering:
    autoscaling:
      enabled: false

#############################################################
# pingdirectory values
#############################################################
pingdirectory:
  enabled: true
  envs:
    SERVER_PROFILE_PATH: profiles/pingdirectory
    SERVER_PROFILE_URL: https://github.com/pingdevopsprogram/reference-cicd 
    MAKELDIF_USERS: "2000"
  container:
    replicaCount: 1

#############################################################
# pingdataconsole values
#############################################################
pingdataconsole:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingdataconsole
    SERVER_PROFILE_BRANCH: master